local _, L = ...
local locale = GetLocale()

if locale == "ruRU" then
	L["Enemy name"] = "Имя противника"
	L["Config"] = "Настройки"
	L["Set movable"] = "Передвигать рамку"
	L["Click to make frame movable"] = "Нажмите, чтобы сделать рамку неподвижной"
	L["Display name"] = "Отображать имя"
	L["Click to display the name of the interrupted enemy"] = "Нажмите, чтобы отображать имя прерваного противника"
	L["Frame scale: "] = "Размер рамки "
	L["Drag to set frame scale"] = "Ператаскивайте, чтобы установить размер рамки"
	L["Player"] = "Игрок"
	L["Party"] = "Группа"
	L["Player interrupts"] = "Прерывания игрока" 
	L["Party interrupts"] = "Прерывания группы"
	L["Enable"] = "Включить"
	L["Click to enable"] = "Нажмите чтобы включить"
	L["Display time in numbers"] = "Отображать время в цифрах"
	L["Click to display the duratation in numbers (better disable this option if you use addons like OmniCC)"] = "Нажмите чтобы отображать время действия в цифрах (лучше отключить, если вы используете аддоны наподобие OmniCC)"
	L["loaded"] = "загружен"
	L["Current version"] = "Текущая версия"
	L["Type"] = "Введите"
	L["to open configuration"] = "чтобы открыть настройки"
else
	L["Enemy name"] = "Enemy name"
	L["Config"] = "Config"
	L["Set movable"] = "Set movable"
	L["Click to make frame movable"] = "Click to make frame movable"
	L["Display name"] = "Display name"
	L["Click to display the name of the interrupted enemy"] = "Click to display the name of the interrupted enemy"
	L["Frame scale: "] = "Frame scale: "
	L["Drag to set frame scale"] = "Drag to set frame scale"
	L["Player"] = "Player"
	L["Party"] = "Party"
	L["Player interrupts"] = "Player interrupts"
	L["Party interrupts"] = "Party interrupts"
	L["Enable"] = "Enable"
	L["Click to enable"] = "Click to enable"
	L["Display time in numbers"] = "Display time in numbers"
	L["Click to display the duratation in numbers (better disable this option if you use addons like OmniCC)"] = "Click to display the duratation in numbers (better disable this option if you use addons like OmniCC)"
	L["loaded"] = "loaded"
	L["Current version"] = "Current version"
	L["Type"] = "Type"
	L["to open configuration"] = "to open configuration"
end